.TH SECRET 1

.SH NAME
secret \- transfer a file over an encrypted ICMP channel

.SH SYNOPSIS
.B secret
[\fB\-kloqv\fR]
[\fB\-r\fR \fIfilename\fR]
[\fB\-s\fR \fIIP or hostname\fR]

.SH DESCRIPTION
.B secret
uses the ICMP protocol's ECHO_REQUEST datagrams and their data fields to encapsulate and transfer the data of a file.
The data is encrypted using AES\-256\-CBC. The encryption key may be adjusted using \fB\-k\fR.

.B secret
can be used both as the sender and the receiver. Specify \fB\-r\fR and \fB\-s\fR to send a file. Specify \fB\-l\fR
to listen for a transmission and receive a file. The sender specifies the received file name. If a file with the same
name exists in the working directory, it will not be overwritten by default. This can be changed using \fB-o\fR.

.B secret
establishes a transmission either in ONE-WAY mode or in TWO-WAY mode. The ONE-WAY mode is used if the sender cannot
receive ICMP ECHO_REQUEST messages from the receiver (e.g. when it is behind a NAT). In this mode, the sender sends all
the data and does not wait for a confirmation from the receiver. The receiver cannot ask for data to be resent, providing
NO GUARANTEE OF DELIVERY. The TWO-WAY mode is used when ICMP ECHO_REQUEST messages from the receiver can reach the sender.
In this mode, the receiver may ask for missing chunks of data to be resent. This provides a certain degree of guarantee
of delivery. Both parties can confirm whether the transmission is to be considered successful or not.

.SH OPTIONS
.TP
.BR \-k
When specified, the user is asked to interactively provide a custom encryption key before starting the transmission.

.TP
.BR \-l
Triggers the receiver mode. Waits for a transmission starting datagram and then receives data from a sender.
It cannot be used together with \fB-r\fR and \fB-s\fR.

.TP
.BR \-o
Enables the receiver to overwrite an existing file.

.TP
.BR \-q
Disables all output on stdout.

.TP
.BR \-r " " \fIfilename\fR
Sets the path to the file to be sent. Using this option triggers the sender mode. If \fB-r\fR is specified, \fB-s\fR
MUST also be specified. It cannot be used together with \fB-l\fR or \fB-o\fR.

.TP
.BR \-s " " \fIIP\ or\ hostname\fR
Sets the IP address or hostname of the receiver to send the data to. Using this option triggers the sender mode.
If \fB-s\fR is specified, \fB-r\fR MUST also be specified. It cannot be used together with \fB-l\fR or \fB-o\fR.

.TP
.BR \-v
Verbose mode. Enables logging in more detail.

.SH ENVIRONMENT
.B secret
requires OpenSSL version 1.1.1.
